pipeline:
  name: Simran-phase2
  identifier: Simranphase2
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: simrangithubconnectortask3
        repoName: terraform-fnapp-trigger
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: simranaksinfraconnector
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: build-Nodejs-app
                  identifier: buildNodejsapp
                  spec:
                    connectorRef: simrandockerregistryconnectortask3
                    image: node:18-bullseye
                    shell: Sh
                    command: |-
                      # Clone your existing Function App project
                      apt-get update -y
                      apt-get install -y curl apt-transport-https lsb-release gnupg git
                      apt-get install -y git
                      git clone https://github.com/SimranSah1/terraform-fnapp-trigger.git
                      cd terraform-fnapp-trigger

                      # Install dependencies
                      npm install
                      # Clone repo & install dependencies
                      curl -sL https://aka.ms/InstallAzureCLIDeb | bash
                    envVariables:
                      ARM_CLIENT_ID: <+secrets.getValue("ARM_CLIENT_ID_SIMRAN")>
                      ARM_CLIENT_SECRET: <+secrets.getValue("ARM_CLIENT_SECRET_SIMRAN")>
                      ARM_SUBSCRIPTION_ID: <+secrets.getValue("ARM_SUBSCRIPTION_ID_SIMRAN")>
                      ARM_TENANT_ID: <+secrets.getValue("ARM_TENANT_ID_SIMRAN")>
              - step:
                  type: Run
                  name: deploy
                  identifier: deploy
                  spec:
                    connectorRef: simrandockerregistryconnectortask3
                    image: node:18-bullseye
                    shell: Sh
                    command: |-
                      apt-get update -y && \
                      apt-get install -y curl apt-transport-https lsb-release gnupg software-properties-common

                      # -----------------------------
                      # Install Azure CLI
                      # -----------------------------
                      curl -sL https://aka.ms/InstallAzureCLIDeb | bash
                      az version

                      # -----------------------------
                      # Install Node.js 18 (LTS)
                      # -----------------------------
                      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
                      apt-get install -y nodejs
                      node -v
                      npm -v

                      # -----------------------------
                      # Install Azure Functions Core Tools v4
                      # -----------------------------
                      npm install -g azure-functions-core-tools@4 --unsafe-perm true
                      func --version

                      # -----------------------------
                      # Azure Login using Harness secrets
                      # -----------------------------

                      set -e  # Exit immediately on error

                      echo "=== Azure CLI Login ==="

                      # Write secret to a file (avoids parsing issues)
                      echo "$ARM_CLIENT_SECRET" > /tmp/secret.txt

                      # Login using Service Principal
                      az login --service-principal \
                        --username "$ARM_CLIENT_ID" \
                        --password "$(cat /tmp/secret.txt)" \
                        --tenant "$ARM_TENANT_ID"

                      # Optional: remove the file for security
                      rm -f /tmp/secret.txt

                      # Set subscription if provided
                      if [[ -n "$ARM_SUBSCRIPTION_ID" ]]; then
                          echo "=== Setting Azure Subscription ==="
                          az account set --subscription "$ARM_SUBSCRIPTION_ID"
                      fi

                      echo "=== Azure CLI Login Successful ==="
                      # -----------------------------
                      # Navigate to build artifact & Deploy
                      # -----------------------------
                      cd /harness/your-build-artifact-folder
                      func azure functionapp publish harnessfnapp --typescript
                    envVariables:
                      ARM_CLIENT_ID: <+secrets.getValue("ARM_CLIENT_ID_SIMRAN")>
                      ARM_CLIENT_SECRET: <+secrets.getValue("ARM_CLIENT_SECRET_SIMRAN")>
                      ARM_SUBSCRIPTION_ID: <+secrets.getValue("ARM_SUBSCRIPTION_ID_SIMRAN")>
                      ARM_TENANT_ID: <+secrets.getValue("ARM_TENANT_ID_SIMRAN")>
